apiVersion: v1
kind: Service
metadata:
  name: alertmanager-nodeport
  namespace: monitoring-infra
  labels:
    app: alertmanager
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: monitoring-kube-prometheus-alertmanager
  ports:
    - name: http-web
      port: 9093
      targetPort: 9093
      nodePort: 30903

